### ISSUE TITLE
Panic for too-big collections

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#540]
When allocating memory for a new `List`, `Str`, `Set`, or `Dict` two things can go wrong:

1. `malloc` returns `null`, indicating the system has run out of heap space.
2. The capacity of the collection exceeds [`isize::MAX`](https://doc.rust-lang.org/nightly/std/primitive.isize.html#associatedconstant.MAX) bytes, meaning it has exceeded the maximum addressable bytes. (Note that it's `isize::MAX` and not `usize::MAX` because memory offsets use signed arithmetic.)

If either of these happen, we should panic. The alternative would be undefined behavior!

In the case of a literal that's too long (e.g. someone actually wrote out a multi-gigabyte string in their `.roc` file), we should report this at compile time instead of panicking.

### TODO
- [ ] Verify that we panic whenever a `roc_alloc` call returns `null`
- [ ] Panic whenever a `Str`, `List`, `Dict`, or `Set` would have capacity of more than `isize::MAX` bytes (note: *bytes*,  not elements!) - we should do this "overflow" check on all operations that can increase capacity, e.g. `append`, `prepend`, `concat`, `reserve`, `withCapacity`, etc.
- [ ] Report a compile-time error and code-gen a `RuntimeError` whenever a literal for one of these would be more than `isize::MAX` bytes (again, *bytes*, not elements)
